/** Declaration file generated by dts-gen */
declare module 'juicer' {
    export = juicer;

    declare function juicer(...args: any[]): string;

    declare namespace juicer {
        const documentHTML: string;

        const options: {
            cache: boolean;
            detection: boolean;
            errorhandling: boolean;
            strip: boolean;
        };

        const settings: {
            elseifstart: RegExp;
            elsestart: RegExp;
            forend: RegExp;
            forstart: RegExp;
            helperRegister: RegExp;
            ifend: RegExp;
            ifstart: RegExp;
            include: RegExp;
            inlinecomment: RegExp;
            interpolate: RegExp;
            noneencode: RegExp;
            rangestart: RegExp;
        };

        const tags: {
            commentClose: string;
            commentOpen: string;
            interpolateClose: string;
            interpolateOpen: string;
            noneencodeClose: string;
            noneencodeOpen: string;
            operationClose: string;
            operationOpen: string;
        };

        const version: string;

        function compile(tpl: any, options: any): any;

        function register(fname: any, fn: any): any;

        function set(conf: any, value?: any, ...args: any[]): any;

        function tagInit(): void;

        function template(options: any): any;

        function to_html(tpl: any, data: any, options: any): any;

        function unregister(fname: any): any;

    }
}
